Changes Jeroen multi xtdb
minvws/nl-kat-octopoes pull request #20
Opened 2022-12-14 17:57 UTC by Rieven

2022-12-20 09:26 UTC, underdarknl requested changes

2022-12-20 09:26 UTC, underdarknl commented on octopoes/xtdb/client.py
> +            data=json.dumps({"node": name}),
Maybe directly use the json attribute? This will inject the correct content-type headers automatically, and removed the need to dump to json first.

2022-12-20 09:32 UTC, ammar92 commented on octopoes/api/router.py
> +            raise HTTPException(status_code=404, detail="Node does not exist")
Try to avoid magic numbers. Reuse `HTTPStatus.NOT_FOUND` or even better:

```python3
from fastapi import status

status.HTTP_404_NOT_FOUND
```

2022-12-20 09:42 UTC, underdarknl commented on octopoes/core/app.py
> +    else:
Please add a comment why this special case is present.

2022-12-22 10:48 UTC, ammar92 approved these changes

2023-01-06 13:59 UTC, underdarknl approved these changes

2023-01-06 15:09 UTC, underdarknl approved these changes

2023-01-06 15:10 UTC, merged